services:
  redis:
    image: redis:6-alpine
    ports:
      - '6379:6379'
  mysql:
    image: mysql:8.4
    volumes:
      - ./db/8:/var/lib/mysql
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_ROOT_HOST=%
    restart: always
    command: --default-time-zone='Asia/Singapore'
  mqnamesrv:
    image: apache/rocketmq
    container_name: mqnamesrv
    network_mode: host
    ports:
      - '9876:9876'
    environment:
      - JAVA_OPT=-Xms512m -Xmx512m -Xmn256m
    logging:
      options:
        max-size: '10m'
        max-file: '5'
    volumes:
      - rocketmq-data:/opt/rocketmq/
      - ./conf/logback_namesrv.xml:/opt/rocketmq/conf/logback.xml
    command: sh mqnamesrv
  mqbroker:
    image: apache/rocketmq
    container_name: mqbroker
    network_mode: host
    ports:
      - '10911:10911'
      - '10909:10909'
    environment:
      - JAVA_OPT_EXT=-Xms512m -Xmx512m -Xmn256m
      - NAMESRV_ADDR=127.0.0.1:9876
    logging:
      options:
        max-size: '10m'
        max-file: '5'
    volumes:
      - rocketmq-data:/opt/rocketmq/store
      - ./config/logback_broker.xml:/opt/rocketmq/conf/logback.xml
      - ./config/broker.conf:/opt/rocketmq/conf/broker.conf
    command: sh mqbroker -c /opt/rocketmq/conf/broker.conf
  rocketmq-dashboard:
    image: apacherocketmq/rocketmq-dashboard:latest
    container_name: rocketmq-dashboard
    environment:
      - JAVA_OPTS=-Drocketmq.namesrv.addr=127.0.0.1:9876 -Xms512m -Xmx512m
    ports:
      - '8080:8080'
    depends_on:
      - mqnamesrv
      - mqbroker
    network_mode: host
  rabbitmq:
    build:
      context: ./rabbitmq
    container_name: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=123456
    ports:
      - '5672:5672'
      - '15672:15672'
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
  nexus:
    image: sonatype/nexus3
    container_name: nexus
    ports:
      - '8081:8081'
    volumes:
      - ./nexus-data:/nexus-data
  pdf-util:
    image: swr.ap-southeast-3.myhuaweicloud.com/ccpay/pdf-util:test
    container_name: pdf-util
    ports:
      - '5100:5000'
  nginx:
    image: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - '10000:80'

volumes:
  rocketmq-data:
  rabbitmq_data:
