services:
  redis:
    image: redis:6-alpine
    ports:
      - '6379:6379'
  redis-stack:
    image: redis/redis-stack:latest
    volumes:
      - redis-stack-data:/data
    ports:
      - '7369:6379'
      - '8001:8001'

  neo4j:
    image: neo4j:5.26.6-ubi9
    container_name: neo4j
    ports:
      - '7474:7474' # HTTP
      - '7687:7687' # Bolt
    environment:
      - NEO4J_AUTH=none
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
  mysql:
    image: mysql:8.4.4
    volumes:
      - ./db/8:/var/lib/mysql
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_ROOT_HOST=%
    restart: always
    command: --default-time-zone='Asia/Singapore'
  mqnamesrv:
    image: apache/rocketmq
    container_name: mqnamesrv
    network_mode: host
    ports:
      - '9876:9876'
    environment:
      - JAVA_OPT=-Xms512m -Xmx512m -Xmn256m
    logging:
      options:
        max-size: '10m'
        max-file: '5'
    volumes:
      - rocketmq-data:/opt/rocketmq/
      - ./conf/logback_namesrv.xml:/opt/rocketmq/conf/logback.xml
    command: sh mqnamesrv
  mqbroker:
    image: apache/rocketmq
    container_name: mqbroker
    network_mode: host
    ports:
      - '10911:10911'
      - '10909:10909'
    environment:
      - JAVA_OPT_EXT=-Xms512m -Xmx512m -Xmn256m
      - NAMESRV_ADDR=127.0.0.1:9876
    logging:
      options:
        max-size: '10m'
        max-file: '5'
    volumes:
      - rocketmq-data:/opt/rocketmq/store
      - ./config/logback_broker.xml:/opt/rocketmq/conf/logback.xml
      - ./config/broker.conf:/opt/rocketmq/conf/broker.conf
    command: sh mqbroker -c /opt/rocketmq/conf/broker.conf
  rocketmq-dashboard:
    image: apacherocketmq/rocketmq-dashboard:latest
    container_name: rocketmq-dashboard
    environment:
      - JAVA_OPTS=-Drocketmq.namesrv.addr=127.0.0.1:9876 -Xms512m -Xmx512m
    ports:
      - '8080:8080'
    depends_on:
      - mqnamesrv
      - mqbroker
    network_mode: host
  minio:
    image: minio/minio:RELEASE.2025-04-22T22-12-26Z-cpuv1
    container_name: minio
    environment:
      - MINIO_ACCESS_KEY=minio
      - MINIO_SECRET_KEY=minio123
    ports:
      - '9002:9000'
      - '9001:9001'
    volumes:
      - ./minio_data:/data
    command: server /data --console-address ":9001" --json
  rabbitmq:
    build:
      context: ./rabbitmq
    container_name: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=123456
    ports:
      - '5672:5672'
      - '15672:15672'
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
  # cobo-keygen:
  #   build:
  #     context: ./cobo
  #     dockerfile: Dockerfile
  #   image: cobo-keygen
  frpc:
    image: snowdreamtech/frpc:0.62-bookworm
    volumes:
      - ./frpc/frpc.toml:/etc/frp/frpc.toml
    ports:
      - '7000:7000'
      - '7500:7500'
  elasticsearch:
    image: elasticsearch:8.18.2
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - 'ES_JAVA_OPTS=-Xms512m -Xmx512m'
    ports:
      - '9200:9200'
      - '9300:9300'
    volumes:
      - es_data:/usr/share/elasticsearch/data

  # nexus:
  #   image: sonatype/nexus3
  #   container_name: nexus
  #   ports:
  #     - '8081:8081'
  #   volumes:
  #     - ./nexus-data:/nexus-data
  # pdf-util:
  #   image: swr.ap-southeast-3.myhuaweicloud.com/ccpay/pdf-util:test
  #   container_name: pdf-util
  #   ports:
  #     - '5100:5000'
  nginx:
    image: nginx
    network_mode: host
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
  # nacos:
  #   image: hyperagi/nacos-client:last
  #   environment:
  #     - PUBLIC_IP=43.159.42.232
  #     - NODE=43.159.42.232:2
  #     - PORT=1082
  #     - WALLET_ADDRESS=0xaaC73e223DEc87218d849992b73B52be81910cAc
  #     - SERVICE_NAME=MFDoom/deepseek-r1-tool-calling:32b
  #   restart: always

volumes:
  rocketmq-data:
  rabbitmq_data:
  redis-stack-data:
  neo4j_data:
  neo4j_logs:
  es_data:
